### ISSUE TITLE
[Feat] 회원 가입

### ISSUE THREAD

**Issue by YiBeomSeok** [CaZaIt/CaZaIt-Android-Private#11]
## SignUpActivity

- [x] 기존 정규식 적용
- [x] 이메일 중복확인 API 작성
- [x] 이메일 중복확인 가능
- [x] 닉네임 중복확인 API 작성
- [x] 닉네임 중복확인 가능
- [x] 가입하기 API 작성
- [x] 가입하기 가능

## activity_sign_up
- [x]  경고 문구 해결

**Comment by dlrlfgh1210** [comment]
SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\umc_kotlin_cazait\CaZaIt-Android-Private\local.properties'.
에러 메시지때문에 수정할 예정

**Comment by WooBinHam** [comment]
기존 코드를 활용하여 회원가입 api 까지는 작성.
회원가입이 완료 되면 이메일 중복과 닉네임 중복 확인 가능 api 및 기능 구현 예정
