### ISSUE TITLE
[Feat] Auth

### ISSUE THREAD

**Issue by YiBeomSeok** [CaZaIt/CaZaIt-Android-Private#12]
## SignIn Activity
- [x] 로그인 API 작성 @WooBinHam 
- [x] 로그인 가능
- [ ] 회원가입 버튼 클릭시 Navigation 적용 @YiBeomSeok 

## activity_sign_in
- [x]  경고 메시지 해결

**Comment by WooBinHam** [comment]
## 해야할 일
- 로그인 버튼 눌렀을 시 서버에 로그인 하겠다고 전송
- 올바르지 않을 시에 올바르지 않다는 메시지가 나오도록 작성

**Comment by WooBinHam** [comment]
[Dagger/MissingBinding] org.cazait.network.NetworkConnectivity cannot be provided without an @Provides-annotated method.

실행 시 위와 같은 메시지가 뜨는데 해결해봐야 할듯 함

**Comment by WooBinHam** [comment]
# Issue 삭제시
로그인 관련 기능이 완벽하게 구현되면 삭제하면 좋을듯.

**Comment by YiBeomSeok** [comment]
# 로그인

- [ ] 로그인 하기 버튼 클릭 시 SignIn Activity 실행
