### ISSUE TITLE
[Feat] 카페 검색 기능 제공

### ISSUE THREAD

**Issue by YiBeomSeok** [CaZaIt/CaZaIt-Android-Private#98]
- 검색 버튼 적용
- 검색 창 페이지 추가
- API 적용

**Comment by WooBinHam** [comment]
## 변경사항
- fragment_cafe_list.xml에서 SearchBar를 기존 EditText에서 TextView로 변경 (TextView 클릭시 검색을 위한 새로운 Activity로 이동)
- CafeListFragment에서 SearchActivity로 이동하면 EditText 자동 활성화되어서 바로 검색할 수 있게끔 변경

**Comment by WooBinHam** [comment]
## 추가로 해야할 작업
- [x] 검색 중간에 관련 아이템 클릭시 해당 아이템의 상세정보로 이동
- [x] 검색 후 엔터 치면 "OOO 검색결과"와 함께 관련 리스트 출력
